- hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  roles:
    - nginx_react
    - react_app_deploy

  tasks:

    - name: Attach instance to target group
      community.aws.elb_target:
        target_group_arn: "{{ target_group_arn }}"
        target_id: "{{ ansible_ec2_instance_id }}"
        state: present
        region: eu-central-1
